global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: kafka-broker
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'kafka-0:8080'
          - 'kafka-1:8080'
          - 'kafka-2:8080'
